; MICROCONTROLADORES
; UFAM - 2019/1
; AUTOR: PATRICK CHAGAS DOS SANTOS

; PIC16F628A Configuration Bit Settings

; Assembly source line config statements

#include "p16f628a.inc"

; CONFIG
; __config 0xFF61
 __CONFIG _FOSC_XT & _WDTE_OFF & _PWRTE_ON & _MCLRE_OFF & _BOREN_ON & _LVP_OFF & _CPD_OFF & _CP_OFF
 
 ;
 ; PAGINAÇÃO DE MEMÓRIA
 ;
 
 #DEFINE	BANK0  BCF STATUS,RP0				;SETA BANK 0 DE MEMÓRIA
 #DEFINE	BANK1  BSF STATUS,RP0  				;SETA BANK 1 DE MEMÓRIA
 
 ;
 ; DEFINIÇÃO DE VARIÁVEIS
 ;
 
 CBLOCK 0X20  							;ENDEREÇO INICIAL DA MEMÓRIA DE USUÁRIO
 d1
 d2
 d3
 ENDC  								;FIM DO BLOCO DE MEMÓRIA
 
 ; --- DEFINIÇÃO DE PINOS DE ENTRADA ---
 
 ; BOTÃO PARA SOLICITAR ABERTURA DA PORTA PELA PARTE INTERNA
 ; 0: SIM 
 ; 1: NÃO
 #DEFINE 	BT_ABRIR_DENTRO		PORTB,0  
 
 ; BOTÃO PARA SOLICITAR ABERTURA DA PORTA PELA PARTE EXTERNA
 ; 0: SIM 
 ; 1: NÃO
 #DEFINE 	BT_ABRIR_FORA		PORTB,1
 
 ; CHAVE DE FIM DE CURSO PARA INDICAR PORTA ABERTA
 ; 0: SIM
 ; 1: NÃO
 #DEFINE 	BT_PORTA_ABERTA		PORTB,2      
 
 ; CHAVE DE FIM DE CURSO PARA INDICAR PORTA FECHADA
 ; 0: SIM
 ; 1: NÃO
 #DEFINE 	BT_PORTA_FECHADA	PORTB,3

 ; SENSOR DE BARREIRA DE LUZ INTERROMPIDA
 ; 0: SIM
 ; 1: NÃO
 #DEFINE 	BARREIRA		PORTB,4 
 
 ; CHAVE PARA SIMULAR INTERRUPÇÃO DA BARREIRA DE LUZ
 ; 0: SIM
 ; 1: NÃO
 #DEFINE 	OBSTRUCAO		PORTB,5 
 
 ; LED PARA SIMULAR FUNCIONAMENTO DO MOTOR DA PORTA 
 ; 0: SIM
 ; 1: NÃO
 #DEFINE 	MOTOR_PORTA		PORTB,6

 ; LED PARA SIMULAR MENSAGEM DO MOTORISTA 
 ; 0: SIM
 ; 1: NÃO
 #DEFINE 	MENSAGEM		PORTB,7

 
 
 
 ; --- DEFINIÇÃO DE PINOS PARA CONTROLE DA RAMPA DE ACESSO ---
 
 ; SIMULA O SINAL DE ESTENDER RAMPA 
 ; 0: DESLIGADO
 ; 1: LIGADO
 #DEFINE 	BT_ESTENDER_RAMPA	PORTA,0        

 ; SIMULA O SINAL DE RECOLHER RAMPA
 ; 0: DESLIGADO
 ; 1: LIGADO
 #DEFINE 	BT_RECOLHER_RAMPA	PORTA,1
 
  ; SIMULA O SINAL DE RAMPA PLATAFORMA 
 ; 0: DESLIGADO
 ; 1: LIGADO
 #DEFINE 	BT_RAMPA_PLATAFORMA	PORTA,2        

 ; SIMULA O SINAL DE RAMPA FORA
 ; 0: DESLIGADO
 ; 1: LIGADO
 #DEFINE 	BT_RAMPA_FORA		PORTA,3
 
  ; SIMULA O SINAL DE RAMPA DENTRO 
 ; 0: DESLIGADO
 ; 1: LIGADO
 #DEFINE 	BT_RAMPA_DENTRO		PORTA,4  

 ; SIMULA O MOTOR DA RAMPA 
 ; 0: DESLIGADO
 ; 1: LIGADO
 #DEFINE 	MOTOR_RAMPA		PORTA,5  
 
 ; --- VETOR DE RESET ---
      ORG 0X00  				;ENDEREÇO INICIAL
      GOTO INICIO
 
 ; --- VETOR DE INTERRUPÇÃO ---
      ORG 0X04
      RETFIE  					;RETORNA DA INTERRUPÇÃO
 
 ; --- PROGRAMA PRINCIPAL ---

 INICIO:
      CLRF  PORTA
      CLRF  PORTB
   
      BANK1
      MOVLW B'00111111'				;RB0 A RB5  COMO ENTRADA E RB6,7 COMO SAÍDA
      MOVWF TRISB
   
      MOVLW B'11011111'				;RA0 E RA4 COMO ENTRADA PARA CONTROLE DA RAMPA DE ACESSO, RA5 COMO SAÍDA	
      MOVWF TRISA
   
      BANK0

 ; --- MAIN ---
 
 MAIN
      CALL 	ABRIR_PORTA			
      CALL	FECHAR_PORTA
      CALL	CONTROLE_RAMPA
      GOTO	MAIN
 
 ;
 ; CONJUNTO DE INTRUÇÕES PARA ABRIR PORTA EM LOOP
 ;
 ABRIR_PORTA:
      CALL	SET_ESPERA_2_SEGUNDOS
      CALL	VERIFICA_ABRIR_DENTRO
      RETURN
 
 ;
 ; CONJUNTO DE INSTRUÇÕES PARA ABRIR PORTA CASO O PASSAGEIRO TENHA SOLICITADO ABERTURA PELO LADO DE DENTRO
 ;      
 VERIFICA_ABRIR_DENTRO:
      BTFSC 	BT_ABRIR_DENTRO				;BT ABRIR_DENTRO FOI PRESSIONADO?
      GOTO	VERIFICA_ABRIR_FORA			;NÃO, CHAMA ROTINA PARA VERIFICAR SE ALGUEM PRESSIONOU O ABRIR_FORA 
      CALL	LIGA_MOTOR_PORTA  			;SIM, CHAMA ROTINA PARA LIGAR O MOTOR
      CALL	VERIFICA_PORTA_ABERTA			;CHAMA ROTINA PARA VERIFICAR A SITUAÇÃO DA ABERTURA DA PORTA
      CALL	DESLIGA_MOTOR_PORTA			;DESLIGA O MOTOR DA PORTA
      RETURN
 
 ;
 ; CONJUNTO DE INSTRUÇÕES PARA ABRIR PORTA CASO O PASSAGEIRO TENHA SOLICITADO ABERTURA PELO LADO DE FORA
 ; 
 VERIFICA_ABRIR_FORA:
      BTFSC 	BT_ABRIR_FORA				;BT ABRIR_FORA FOI PRESSIONADO?
      GOTO	VERIFICA_ABRIR_DENTRO			;NÃO, ENTÃO VERIFICA SE O ABRIR_DENTRO FOI PRESSIONADO	
      CALL  	LIGA_MOTOR_PORTA			;SIM, CHAMA ROTINA PARA LIGAR O MOTOR DA PORTA	
      CALL	VERIFICA_PORTA_ABERTA  			;CHAMA ROTINA PARA VERIFICAR A SITUAÇÃO DA ABERTURA DA PORTA	
      CALL 	DESLIGA_MOTOR_PORTA			;DESLIGA O MOTOR DA PORTA
      GOTO	FECHAR_PORTA				;CHAMA ROTINA PARA FECHAR A PORTA
      
 ;
 ; DESLIGA O MOTOR DE ABRIR/FECHAR A PORTA
 ;
 LIGA_MOTOR_PORTA:
      BSF	MOTOR_PORTA				;LIGA MOTOR DA PORTA
      RETURN	
      
 ;
 ; DESLIGA O MOTOR DE ABRIR/FECHAR A PORTA
 ;
 DESLIGA_MOTOR_PORTA:   
      BCF	MOTOR_PORTA				;DESLIGA MOTOR DA PORTA
      RETURN							
 ;
 ; SENSOR DE PORTA ABERTA
 ;
 VERIFICA_PORTA_ABERTA:
      BTFSC	BT_PORTA_ABERTA				;SENSOR DE PORTA ABERTA FOI ACIONADO?
      GOTO	VERIFICA_PORTA_ABERTA			;NÃO, CONTINUA VERIFICANDO
      RETURN						
      
 ;
 ; SENSOR DE PORTA FECHADA
 ;
 VERIFICA_PORTA_FECHADA:
      BTFSC	BT_PORTA_FECHADA			;SENSOR DE PORTA FECHADA FOI ACIONADO?
      GOTO	VERIFICA_PORTA_FECHADA			;NÃO, CONTINUA VERIFICANDO
      RETURN
 ;
 ; CONJUNTO DE INSTRUÇÕES PARA FECHAR A PORTA
 ;
 FECHAR_PORTA:
      CALL	VERIFICA_BARREIRA			;VERIFICA SITUAÇÃO DA BARREIRA DE LUZ
      CALL	ESPERA_2_SEGUNDOS			;AGUARDA POR 2 SEGUNDOS
      CALL	LIGA_MOTOR_PORTA			;LIGA MOTOR PARA INICIAR O FECHAMENTO
      CALL	VERIFICA_PORTA_FECHADA			;CHAMA ROTINA PARA VERIFICAR A SITUAÇÃO DO FECHAMENTO DA PORTA
      CALL	DESLIGA_MOTOR_PORTA			;DESLIGA O MOTOR DA PORTA
      GOTO	VERIFICACAO_DO_MOTORISTA  		;CHAMA ROTINA PARA SIMULAR A VERIFICACAO DO MOTORISTA
 ;
 ; VERIFICA SE A BARREIRA DE LUZ ESTA OBSTRUIDA
 ;
 VERIFICA_BARREIRA:
      BTFSC	BARREIRA				;BARREIRA INTERROMPIDA? (NORMALMENTE = 0)
      GOTO	VERIFICA_BARREIRA			;SIM, CONTINUA VERIFICANDO 
      RETURN						;NÃO,
      
 ;
 ; FUNÇÃO PARA DELAY DE 2 SEGUNDOS
 ;
 ESPERA_2_SEGUNDOS:
      DECFSZ	d1, f
      GOTO	$+2
      DECFSZ	d2, f
      GOTO	$+2
      DECFSZ	d3, f
      GOTO	ESPERA_2_SEGUNDOS
      RETURN
 ;
 ;FUNÇÃO QUE CORRESPONDE A CONFERENCIA DO MOTORISTA
 ;
 VERIFICACAO_DO_MOTORISTA:
      BTFSC	OBSTRUCAO				;EXISTE ALGUMA OBSTRUÇÃO?
      GOTO	MAIN					;NÃO, VAI PARA MAIN 
      GOTO	ACIONA_MENSAGEM				;SIM, ACIONA MENSAGEM
 ;
 ; SIMULA AVISO DO MOTORISTA AOS PASSAGEIROS COM DURAÇÃO DE 2 SEGUNDOS
 ; 
 ACIONA_MENSAGEM:
      BSF	MENSAGEM				;LIGA LED QUE INDICA O ANUNCIO DE MENSAGEM DO MOTORISTA
      CALL	SET_ESPERA_2_SEGUNDOS			;CONFIGURA REGISTRADORES PARA DELAY DE 2S
      CALL	ESPERA_2_SEGUNDOS			;MANTEM ACESSO DURANTE 2 SEGUNDOS	
      BCF	MENSAGEM				;DESLIGA LED
      GOTO	VERIFICACAO_DO_MOTORISTA		;MOTORISTA VERIFICA NOVAMENTE
 ;
 ; CARREGA REGISTRADORES PARA GERAR DELAY DE 2 SEGUNDOS
 ; 
 SET_ESPERA_2_SEGUNDOS:
      ; 1999996 cycles
      MOVLW	0X11
      MOVWF	d1
      MOVLW	0X5D
      MOVWF	d2
      MOVLW	0X05
      MOVWF	d3
      RETURN

 ;;      
 ;; SINAIS DE CONTROLE PARA RAMPA DE ACESSO. CONFORME PREVISTO NO EXERCÍCIO NÃO EXISTE CONEXÃO COM O CONTROLE PRINCIPAL
 ;;      
 CONTROLE_RAMPA:
      CALL	LIGA_ESTENDER_RAMPA			;CHAMA ROTINA PARA VERIFICAR SE DEVE ESTENDER RAMPA	
      CALL	LIGA_RECOLHER_RAMPA			;CHAMA ROTINA PARA VERIFICAR SE DEVE RECOLHER RAMPA
     ; GOTO	CONTROLE_RAMPA				;LOOP
RETURN
 ;
 ; FUNCOES PARA ESTENDER RAMPA
 ;
 LIGA_ESTENDER_RAMPA:
      BTFSC	BT_ESTENDER_RAMPA				;CHEGOU SINAL PARA ESTENDER RAMPA?
      GOTO	CONTROLE_RAMPA				;NÃO, VOLTA PARA LOOP
      CALL	CONTROLE_MOTOR_ESTENDER_RAMPA		;SIM, CHAMA ROTINA DE CONTROLE DO MOTOR QUE ESTENDE RAMPA	 
      RETURN
      
 CONTROLE_MOTOR_ESTENDER_RAMPA:
      BSF	MOTOR_RAMPA				;LIGA MOTOR 
      CALL	VERIFICA_RAMPA_PLATAFORMA		;CHAMA ROTINA PARA VERIFICAR A SITUAÇÃO DA ESTENSÃO DA RAMPA
      BCF	MOTOR_RAMPA				;DESLIGA MOTOR
      RETURN
      
 VERIFICA_RAMPA_PLATAFORMA:
      BTFSC	BT_RAMPA_PLATAFORMA			;SENSOR DE RAMPA_PLATAFORMA FOI ACIONADO?	
      CALL	VERIFICA_RAMPA_FORA			;NÃO, CHAMA ROTINA QUE VERIFICA SENSOR RAMPA_FORA
      RETURN					
      
 VERIFICA_RAMPA_FORA:
      BTFSC	BT_RAMPA_FORA				;SENSOR DE RAMPA_FORA FOI ACIONADO?
      CALL	VERIFICA_RAMPA_PLATAFORMA		;NÃO, CHAMA ROTINA QUE VERIFICA SENSOR RAMPA_PLATAFORMA
      RETURN      
 
 ;
 ; FUNCOES PARA RECOLHER RAMPA
 ;
 LIGA_RECOLHER_RAMPA:
      BTFSC	BT_RECOLHER_RAMPA				;CHEGOU SINAL PARA RECOLHER RAMPA?
      GOTO	CONTROLE_RAMPA				;NÃO, VOLTA PARA LOOP
      GOTO	CONTROLE_MOTOR_RECOLHER_RAMPA		;SIM, CHAMA ROTINA DE CONTROLE DO MOTOR QUE RECOLHE RAMPA	 
 
 CONTROLE_MOTOR_RECOLHER_RAMPA:
      BSF	MOTOR_RAMPA				;LIGA MOTOR	
      CALL	VERIFICA_RECOLHER_RAMPA			;CHAMA ROTINA PARA VERIFICAR A SITUAÇÃO DO RECOLHIMENTO DA RAMPA
      BCF	MOTOR_RAMPA				;DESLIGA MOTOR
      GOTO	CONTROLE_RAMPA				;VAI PARA LOOP
      
 VERIFICA_RECOLHER_RAMPA:
      BTFSC	BT_RAMPA_DENTRO				;SENSOR DE RAMPA_DENTRO FOI ACIONADO?
      GOTO	VERIFICA_RECOLHER_RAMPA			;NÃO, CONTINUA VERIFICANDO
      RETURN
  
END